[advisories]
yanked = "deny"
ignore = [
    { id = "RUSTSEC-2024-0384", reason = "this is about instant crate, which is only used for benchmarks + an upstream fix is in the works." },
]

[licenses]
allow = [
    "MIT-0",
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "Zlib",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
]

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/dimforge/rapier"]
