[advisories]
yanked = "deny"
ignore = [
    # paste was announced as unmaintained with no explanation or replacement
    # See: 
    # - https://rustsec.org/advisories/RUSTSEC-2024-0436
    # - https://github.com/bevyengine/bevy/pull/18209
    # Bevy relies on this in multiple indirect ways, so ignoring it is the only feasible current solution
    "RUSTSEC-2024-0436",
]

[licenses]
allow = [
    "MIT-0",
    "MIT",
    "Apache-2.0",
    "Zlib",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "NCSA",
    "Apache-2.0 WITH LLVM-exception",
]

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/dimforge/rapier"]
